version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - websocket-server

  websocket-server:
    build: ./websocket-server
    ports:
      - "8081:8080"
